### ISSUE TITLE
知识文章建议改为使用 repo 中的若干 .md 文件保存

### ISSUE THREAD

**Issue by ChengCat** [justjavac/the-front-end-knowledge-you-may-not-know#17]
知识文章建议改为使用 repo 中的若干 .md 文件保存，而与此相关的讨论可以在 issues 或 pull request 里进行。

这样可以方便的 `git clone`，也可以通过 pull request 参与改进。

**Comment by justjavac** [comment]
很好的建议，而且可以记录 commit 的 history

**Comment by justjavac** [comment]
谢谢你的建议，并接受了你的建议
