### ISSUE TITLE
Array.isArray(Array.prototype) === true

### ISSUE THREAD

**Issue by swust-xiaoj** [justjavac/the-front-end-knowledge-you-may-not-know#34]
- [Array.prototype](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype)
 - [Why is Array.prototype designed to be a fully functional array](https://softwareengineering.stackexchange.com/a/304734)

想知道为啥这么设计

**Comment by justjavac** [comment]
数组并不特殊吧，JavaScript 的类继承机制就是这样的啊
